name: Product Scraper

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  push:
    branches:
      - main # or your default branch

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add products.csv
          git commit -m "Updated product feed (automated)" || echo "No changes to commit"
          git push
